// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: felight_types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------------------------------------------
// The following messages are for public use.
// -----------------------------------------------------
type Tx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sender of the transaction
	From []byte `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// Encoded raw tx binary
	RawTx []byte `protobuf:"bytes,2,opt,name=raw_tx,json=rawTx,proto3" json:"raw_tx,omitempty"`
}

func (x *Tx) Reset() {
	*x = Tx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_felight_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tx) ProtoMessage() {}

func (x *Tx) ProtoReflect() protoreflect.Message {
	mi := &file_felight_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tx.ProtoReflect.Descriptor instead.
func (*Tx) Descriptor() ([]byte, []int) {
	return file_felight_types_proto_rawDescGZIP(), []int{0}
}

func (x *Tx) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Tx) GetRawTx() []byte {
	if x != nil {
		return x.RawTx
	}
	return nil
}

type TxsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *TxsRequest) Reset() {
	*x = TxsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_felight_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxsRequest) ProtoMessage() {}

func (x *TxsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_felight_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxsRequest.ProtoReflect.Descriptor instead.
func (*TxsRequest) Descriptor() ([]byte, []int) {
	return file_felight_types_proto_rawDescGZIP(), []int{1}
}

func (x *TxsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type TxsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txs []*Tx `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
}

func (x *TxsResponse) Reset() {
	*x = TxsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_felight_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxsResponse) ProtoMessage() {}

func (x *TxsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_felight_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxsResponse.ProtoReflect.Descriptor instead.
func (*TxsResponse) Descriptor() ([]byte, []int) {
	return file_felight_types_proto_rawDescGZIP(), []int{2}
}

func (x *TxsResponse) GetTxs() []*Tx {
	if x != nil {
		return x.Txs
	}
	return nil
}

var File_felight_types_proto protoreflect.FileDescriptor

var file_felight_types_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x65, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x2f, 0x0a, 0x02,
	0x54, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x61, 0x77, 0x5f, 0x74, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x72, 0x61, 0x77, 0x54, 0x78, 0x22, 0x24, 0x0a,
	0x0a, 0x54, 0x78, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x0b, 0x54, 0x78, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x03, 0x74, 0x78, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x54, 0x78, 0x52, 0x03, 0x74, 0x78, 0x73, 0x42,
	0x3d, 0x5a, 0x3b, 0x62, 0x69, 0x74, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x6f, 0x72, 0x67,
	0x2f, 0x6c, 0x65, 0x6f, 0x70, 0x61, 0x72, 0x64, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x66, 0x65, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x64, 0x6b, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_felight_types_proto_rawDescOnce sync.Once
	file_felight_types_proto_rawDescData = file_felight_types_proto_rawDesc
)

func file_felight_types_proto_rawDescGZIP() []byte {
	file_felight_types_proto_rawDescOnce.Do(func() {
		file_felight_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_felight_types_proto_rawDescData)
	})
	return file_felight_types_proto_rawDescData
}

var file_felight_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_felight_types_proto_goTypes = []interface{}{
	(*Tx)(nil),          // 0: types.Tx
	(*TxsRequest)(nil),  // 1: types.TxsRequest
	(*TxsResponse)(nil), // 2: types.TxsResponse
}
var file_felight_types_proto_depIdxs = []int32{
	0, // 0: types.TxsResponse.txs:type_name -> types.Tx
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_felight_types_proto_init() }
func file_felight_types_proto_init() {
	if File_felight_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_felight_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_felight_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_felight_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_felight_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_felight_types_proto_goTypes,
		DependencyIndexes: file_felight_types_proto_depIdxs,
		MessageInfos:      file_felight_types_proto_msgTypes,
	}.Build()
	File_felight_types_proto = out.File
	file_felight_types_proto_rawDesc = nil
	file_felight_types_proto_goTypes = nil
	file_felight_types_proto_depIdxs = nil
}
